apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
  labels:
    app: sre-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
    spec:
      containers:
        - name: sre-app
          image: otus/sre-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: LISTEN_PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: sre-app-service
spec:
  selector:
    app: sre-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort